#ifndef ENTITYIDS__H
#define ENTITYIDS__H

#define PLAYER_ID 0
#define FIRE_BALL_ID 1
#define WIND_SLASH_ID 2
#define ICE_SHARD_ID 3
#define ICE_BLOCK_ID 4
#define CLOUD_ID 5
#define LEAF_ID 6
#define THORNS_ID 7
#define ROCK_ID 8
#define SHOCKWAVE_ID 9

#define FIRE_SPELL_PICKUP_ID 10
#define GROUND_SPELL_PICKUP_ID 11

#define MAX_HEALTH_PICKUP_ID 12
#define MAX_MANA_PICKUP_ID 13

#define GROUNDED_ELEMENTAL_ID 14
#define FLYING_ELEMENTAL_ID 15
#define COAL_JUMPER_ID 16
#define ARMOR_TRAP_ID 17
#define SHIELD_MONSTER_ID 18
#define SHIELD_MONSTER_ID 19
#define CLING_CREATURE_ID 20
#define FLYING_AXE_ID 21
#define FLYING_SHIELD_ID 22
#define CLOUD_MELEE_ID 24
#define CLOUD_SUMMONER_ID 25

#define CLOUD_SUMMONER_PROJECTILE_ID 26
#define HAZARDS_LAVA_ID 27
#define HAZARDS_LAVA_WATERFALL_ID 28
#define HAZARDS_SPIKES_ID 29
#define HAZARDS_ROCK_BLOCK_ID 30
#define HAZARDS_CLOUD_TRAMPOLINE_ID 31

#define CHECKPOINT_ID 32
#define FIRST_DIALOGUE_ID 33
#define TEXTBOXOBJECT_ID 34
#define ENDDEMOOBJECT_ID 35
#define PORTAL_ID 36
#define SPAWNPOINT_ID 37

#endif